[package]
name = "tekerectc"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = "0.23.1"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["cookies", "blocking"] }
dotenv = "0.15.0"
once_cell = "1.21.3"
